name: FN
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - patsy
  - statsmodels
  - yellowbrick
  - biopython
  - pillow
  - logomaker
  - treeswift
  - ete3
  - pip
  - pip:
      - niemads 
